--@formatter:off

-- FamilyDiscount
INSERT INTO FAMILY_DISCOUNT (DISCOUNT) VALUES (3);

--MembershipTypes
INSERT INTO MEMBERSHIP_TYPE (NAME, ANNUAL_FEE) VALUES ( 'Vollmitgliedschaft', 25);
INSERT INTO MEMBERSHIP_TYPE (NAME, ANNUAL_FEE) VALUES ( 'Ermäßigt', 23);
INSERT INTO MEMBERSHIP_TYPE (NAME, ANNUAL_FEE) VALUES ( 'Jugendliche(r)', 15);
INSERT INTO MEMBERSHIP_TYPE (NAME, ANNUAL_FEE) VALUES ( 'Fördermitglied', 10);

--PaymentHistory
INSERT INTO PAYMENT_HISTORY (PAYED, FEE_PAYED, DATE_OF_PAYMENT,YEAR) VALUES (true, 25, '2021-10-16', 2021);
INSERT INTO PAYMENT_HISTORY (PAYED, FEE_PAYED, DATE_OF_PAYMENT,YEAR) VALUES (true, 25, '2021-11-16', 2021);

--Membership
INSERT INTO MEMBERSHIP (START_DATE, END_DATE, CANCELLATION_DATE, MEMBERSHIP_TYPE_ID) VALUES (  '2021-01-01', NULL, NULL,(SELECT ID FROM MEMBERSHIP_TYPE WHERE NAME = 'Vollmitgliedschaft'));
INSERT INTO MEMBERSHIP (START_DATE, END_DATE, CANCELLATION_DATE, MEMBERSHIP_TYPE_ID) VALUES (  '2021-01-01', NULL, NULL,(SELECT ID FROM MEMBERSHIP_TYPE WHERE NAME = 'Vollmitgliedschaft'));

--Members
INSERT INTO MEMBER ( FIRST_NAME, LAST_NAME, POSTAL_CODE, CITY, STREET, STREET_NUMBER, DATE_OF_BIRTH,  IBAN, FAMILY_MEMBER_ID) VALUES ('Hans', 'Wurst', '25336', 'Elmshorn', 'Westerstraße', '50', '1989-10-12',  'DE21301204000000015228', NULL );
INSERT INTO MEMBER ( FIRST_NAME, LAST_NAME, POSTAL_CODE, CITY, STREET, STREET_NUMBER, DATE_OF_BIRTH,  IBAN, FAMILY_MEMBER_ID) VALUES ( 'Marga', 'Rine', '25337', 'Klein Offenseth-Sparrieshoop', 'Rosenstraße', '56', '1945-08-01',   'DE29500105172545755167', NULL);

--Member_Memberships
INSERT INTO MEMBER_MEMBERSHIPS (MEMBER_ID, MEMBERSHIPS_ID) VALUES ((SELECT ID FROM MEMBER WHERE DATE_OF_BIRTH = '1989-10-12'),(SELECT  ID FROM PAYMENT_HISTORY WHERE DATE_OF_PAYMENT = '2021-10-16' AND FEE_PAYED = 25) );
INSERT INTO MEMBER_MEMBERSHIPS (MEMBER_ID, MEMBERSHIPS_ID) VALUES ((SELECT ID FROM MEMBER WHERE DATE_OF_BIRTH = '1945-08-01'),(SELECT  ID FROM PAYMENT_HISTORY WHERE DATE_OF_PAYMENT = '2021-11-16' AND FEE_PAYED = 25));


--Member_Payment_Histories
INSERT INTO MEMBER_PAYMENT_HISTORIES (MEMBER_ID, PAYMENT_HISTORIES_ID) VALUES ((SELECT ID FROM MEMBER WHERE DATE_OF_BIRTH = '1989-10-12'), (SELECT  ID FROM PAYMENT_HISTORY WHERE DATE_OF_PAYMENT = '2021-10-16' AND FEE_PAYED = 25));
INSERT INTO MEMBER_PAYMENT_HISTORIES (MEMBER_ID, PAYMENT_HISTORIES_ID) VALUES ((SELECT ID FROM MEMBER WHERE DATE_OF_BIRTH = '1945-08-01'), (SELECT  ID FROM PAYMENT_HISTORY WHERE DATE_OF_PAYMENT = '2021-11-16' AND FEE_PAYED = 25));

